### ISSUE TITLE
Startseite: unsere Prinzipien

### ISSUE THREAD

**Issue by JuliaKleeberger** [sensebox/Frontend-OpenBadges#3]
Kannst du bitte auf der Startseite unter "Unsere Idee" noch die Sektion einfügen "Unser Ansatz" der in etwa folgendes Aussehe hat: 
![image](https://user-images.githubusercontent.com/12052169/84249541-31664f80-ab0b-11ea-9ad2-c18546b1aad8.png)
Hier auch noch mal die Texte als Klartext: 

Unser Ansatz

Unser Feedbacksystem motiviert die Teilnehmenden mit Freude zu lernen und verhilft ihnen zu einer realistischen Selbsteinschätzung ihres eigenen Fortschritts. Gleichzeitig bietet es der Lernbegleitung Orientierung über den Leistungsstand und bildet damit eine wichtige Grundlage für die weitere didaktisch-pädagogische Planung des Lernprozesses. 

#offen
Andere Einrichtungen können das System entsprechend ihrer Bildungsangebote ausbauen und weiterentwickeln.

#transparent & flexibel
Der Lernende hat Einblick über sein Portfolio und kann selbstbestimmt entscheiden, wem er welche Informationen zur Verfügung stellt

#standardisiert
Durch den Zusammenschluss verschiedener Bildungsakteure wird ein Standardisierungswerkzeug geschaffen, das Orientierung bietet.

#motivierend
“Portfolio & Badges” sind eine Form der Leistungsdarstellung; nicht der Bewertung. Sie fördern die Wertschätzung für die erworbenen Kompetenzen und steigern die Selbstverantwortung des Lernenden.

#digital & dezentral
Wir setzen auf etablierte technische Standards auf, mit denen Kompetenznachweise digital erstellt und dezentral verwaltet werden können. 

#individuell
“Portfolio & Badges” können die individuellen Lernwege dokumentieren und fördern somit das selbstbestimmte, lebenslange Lernen.

**Comment by JuliaKleeberger** [comment]
Die Icons sind noch Platzhalter. Ich such dir noch welche raus - wo soll ich die am besten ablegen? Ich könnte auf dem Drive einen Ordner anlegen - passt das?

**Comment by Delucse** [comment]
- [ ] icons left
