### ISSUE TITLE
Badge erstellen

### ISSUE THREAD

**Issue by JuliaKleeberger** [sensebox/Frontend-OpenBadges#6]
Hallo Felix, ich wollte gerade ein Projekt erstellen - das ging aber irgendwie nicht, weil ich dafür wohl erst Badges anlegen/ festlegen muss (s. Screenshot). Das wird aus dem Projekt-erstellen-Seite aber nicht wirklich ersichtlich ... 

Wenn ich dann einen Badge erstellen will, fragt er mich, nach lokal oder global - das kann ich aber nirgendwo angeben (s. Screenshot 2) ... also kann ich weder einen Badge noch ein Projekt erstellen .... Was muss ich tun?

![Bildschirmfoto 2020-06-17 um 22 28 48](https://user-images.githubusercontent.com/12052169/84947213-1fc40f80-b0ea-11ea-81c2-a91032447bca.png)
![Bildschirmfoto 2020-06-17 um 22 05 47](https://user-images.githubusercontent.com/12052169/84947226-23f02d00-b0ea-11ea-898e-63184232280d.png)

**Comment by Delucse** [comment]
Hallo Julia,
es ist richtig, dass man in einem Projekt aktuell nur Badges auswählen kann, bei denen man die Berechtigung hat, diese selbst auch zu vergeben. Man muss also dies vorab sicherstellen. Die Berechtigung erlangt man einerseits indem man selber einen Badge erstellt (Fehler im Frontend wurde diesbezüglich korrigiert) und andererseits eine Anfrage stellt (über "/badges" auf das Plus-Zeichen klicken beim jeweiligen Badge. Diese Anfrage muss dann bestätigt werden).

Die Unterscheidung zwischen lokalen und globalen Badges werde ich in den nächsten Tagen überarbeiten und man wird stattdessen vorläufig die Kategorien Achievement, Fachkompetenz und Metaskill vorfinden.
